export const TOP_200_COMMON_WORDS_EU: readonly string[] = [
  'eta', 'da', 'bat', 'ez', 'bai', 'zer', 'nola', 'non', 'noiz', 'zergatik',
  'nork', 'zein', 'hau', 'hori', 'hura', 'ni', 'zu', 'gu', 'zuek', 'haiek',
  'izan', 'egon', 'ukan', 'egin', 'etorri', 'joan', 'eman', 'hartu', 'ikusi', 'entzun',
  'jakin', 'nahi', 'behar', 'ahal', 'uste', 'esan', 'pentsatu', 'lagundu', 'bilatu', 'aurkitu',
  'gizon', 'emakume', 'haur', 'familia', 'etxe', 'lan', 'egun', 'gau', 'denbora', 'urte',
  'aste', 'hilabete', 'bizitza', 'herrialde', 'mundua', 'hiria', 'lekua', 'izena', 'zenbakia', 'hizkuntza',
  'historia', 'maitasuna', 'bakea', 'gerra', 'lagun', 'etsaia', 'janaria', 'ura', 'sua', 'lurra',
  'airea', 'eguzkia', 'ilargia', 'izarra', 'mendia', 'itsasoa', 'ibaia', 'zuhaitza', 'lorea', 'gorria',
  'zuria', 'beltza', 'urdina', 'berdea', 'horia', 'bat', 'bi', 'hiru', 'lau', 'bost',
  'sei', 'zazpi', 'zortzi', 'bederatzi', 'hamar', 'ehun', 'mila', 'handia', 'txikia', 'ona',
  'txarra', 'berria', 'zaharra', 'azkarra', 'motela', 'beroa', 'hotza', 'luzea', 'laburra', 'pozik',
  'tristea', 'indartsua', 'ahula', 'erraza', 'zaila', 'argia', 'iluna', 'gaur', 'atzo', 'bihar',
  'orain', 'hemen', 'han', 'hurbil', 'urrun', 'goian', 'behean', 'aurrean', 'atzean', 'eskuinean',
  'ezkerrean', 'ere', 'bakarrik', 'beti', 'batzuetan', 'inoiz ez', 'asko', 'agian', 'noski', 'benetan',
  'beraz', 'nola', 'zergatik', 'noiz', 'non', 'nor', 'zer', 'bihotza', 'begia', 'eskua',
  'burua', 'gorputza', 'osasuna', 'gaixotasuna', 'eskola', 'unibertsitatea', 'liburua', 'zientzia', 'ezagutza', 'erlijioa',
  'otoitza', 'meskita', 'eliza', 'gobernua', 'presidentea', 'legea', 'eskubidea', 'askatasuna', 'justizia', 'demokrazia',
  'ekonomia', 'dirua', 'merkatura', 'merkataritza', 'bidea', 'autoa', 'hegazkina', 'trena', 'musika', 'kirola',
  'artea', 'filma', 'antzerkia', 'kolorea', 'forma', 'neurria', 'pisua', 'abiadura', 'energia', 'indarra',
  'arazoa', 'konponketa', 'emaitza', 'arrazoia', 'eragina', 'aldea', 'antzekotasuna', 'konparaketa', 'adibidea', 'ideia',
];
