export const TOP_200_COMMON_WORDS_MS: readonly string[] = [
  'dan', 'di', 'yang', 'ini', 'itu', 'dengan', 'untuk', 'tidak', 'ada', 'dari',
  'ke', 'pada', 'dalam', 'juga', 'tetapi', 'atau', 'kerana', 'sudah', 'boleh', 'akan',
  'dia', 'mereka', 'kita', 'saya', 'kamu', 'anda', 'ia', 'satu', 'dua', 'oleh',
  'adalah', 'menjadi', 'melakukan', 'mengatakan', 'mengetahui', 'melihat', 'pergi', 'datang', 'memberikan', 'mengambil',
  'berfikir', 'ingin', 'dapat', 'perlu', 'nampak', 'bercakap', 'mendengar', 'membaca', 'menulis', 'makan',
  'minum', 'tidur', 'berjalan', 'berlari', 'belajar', 'membeli', 'menjual', 'membantu', 'lelaki', 'perempuan',
  'kanak-kanak', 'keluarga', 'rumah', 'pekerjaan', 'hari', 'malam', 'masa', 'tahun', 'minggu', 'bulan',
  'hidup', 'negara', 'dunia', 'bandar', 'tempat', 'nama', 'nombor', 'bahasa', 'sejarah', 'cinta',
  'damai', 'perang', 'kawan', 'musuh', 'makanan', 'air', 'api', 'tanah', 'udara', 'matahari',
  'bulan', 'bintang', 'gunung', 'laut', 'sungai', 'pokok', 'bunga', 'merah', 'putih', 'hitam',
  'biru', 'hijau', 'kuning', 'satu', 'dua', 'tiga', 'empat', 'lima', 'enam', 'tujuh',
  'lapan', 'sembilan', 'sepuluh', 'seratus', 'seribu', 'besar', 'kecil', 'baik', 'buruk', 'baru',
  'lama', 'cepat', 'perlahan', 'panas', 'sejuk', 'panjang', 'pendek', 'gembira', 'sedih', 'kuat',
  'lemah', 'mudah', 'susah', 'cerah', 'gelap', 'hari ini', 'semalam', 'esok', 'sekarang', 'di sini',
  'di sana', 'dekat', 'jauh', 'atas', 'bawah', 'depan', 'belakang', 'kanan', 'kiri', 'juga',
  'hanya', 'selalu', 'kadang-kadang', 'tidak pernah', 'banyak', 'mungkin', 'tentu', 'sungguh', 'jadi', 'bagaimana',
  'mengapa', 'bila', 'di mana', 'siapa', 'apa', 'jantung', 'mata', 'tangan', 'kepala', 'badan',
  'kesihatan', 'penyakit', 'sekolah', 'universiti', 'buku', 'sains', 'pengetahuan', 'agama', 'doa', 'masjid',
  'gereja', 'kerajaan', 'presiden', 'undang-undang', 'hak', 'kebebasan', 'keadilan', 'demokrasi', 'ekonomi', 'wang',
  'pasaran', 'perdagangan', 'jalan', 'kereta', 'kapal terbang', 'kereta api', 'muzik', 'sukan', 'seni', 'filem',
];
