export const TOP_200_COMMON_WORDS_HU: readonly string[] = [
  'és', 'a', 'az', 'van', 'hogy', 'nem', 'is', 'de', 'ez', 'egy',
  'az', 'ő', 'ők', 'mi', 'én', 'te', 'ön', 'lenni', 'csinálni', 'mondani',
  'tudni', 'látni', 'menni', 'jönni', 'adni', 'venni', 'gondolni', 'akarni', 'tudni', 'kell',
  'látszik', 'beszélni', 'hallgatni', 'olvasni', 'írni', 'enni', 'inni', 'aludni', 'sétálni', 'futni',
  'tanulni', 'venni', 'eladni', 'segíteni', 'férfi', 'nő', 'gyerek', 'család', 'ház', 'munka',
  'nap', 'éjjel', 'idő', 'év', 'hét', 'hónap', 'élet', 'ország', 'világ', 'város',
  'hely', 'név', 'szám', 'nyelv', 'történelem', 'szerelem', 'béke', 'háború', 'barát', 'ellenség',
  'étel', 'víz', 'tűz', 'föld', 'levegő', 'nap', 'hold', 'csillag', 'hegy', 'tenger',
  'folyó', 'fa', 'virág', 'piros', 'fehér', 'fekete', 'kék', 'zöld', 'sárga', 'egy',
  'kettő', 'három', 'négy', 'öt', 'hat', 'hét', 'nyolc', 'kilenc', 'tíz', 'száz',
  'ezer', 'nagy', 'kis', 'jó', 'rossz', 'új', 'régi', 'gyors', 'lassú', 'meleg',
  'hideg', 'hosszú', 'rövid', 'boldog', 'szomorú', 'erős', 'gyenge', 'egyszerű', 'nehéz', 'fényes',
  'sötét', 'ma', 'tegnap', 'holnap', 'most', 'itt', 'ott', 'közel', 'messze', 'fent',
  'lent', 'előtt', 'mögött', 'jobbra', 'balra', 'is', 'csak', 'mindig', 'néha', 'soha',
  'sok', 'talán', 'persze', 'valóban', 'ezért', 'hogyan', 'miért', 'mikor', 'ahol', 'ki',
  'mi', 'szív', 'szem', 'kéz', 'fej', 'test', 'egészség', 'betegség', 'iskola', 'egyetem',
  'könyv', 'tudomány', 'tudás', 'vallás', 'ima', 'mecset', 'templom', 'kormány', 'elnök', 'törvény',
  'jog', 'szabadság', 'igazságosság', 'demokrácia', 'gazdaság', 'pénz', 'piac', 'kereskedelem', 'út', 'autó',
  'repülő', 'vonat', 'zene', 'sport', 'művészet', 'film', 'színház', 'szín', 'forma', 'méret',
  'súly', 'sebesség', 'energia', 'erő', 'probléma', 'megoldás', 'eredmény', 'ok', 'hatás', 'különbség',
];
