export const TOP_200_COMMON_WORDS_FI: readonly string[] = [
  'ja', 'on', 'ei', 'että', 'se', 'myös', 'mutta', 'jos', 'mitä', 'niin',
  'hän', 'he', 'me', 'minä', 'sinä', 'te', 'olla', 'tehdä', 'sanoa', 'tietää',
  'nähdä', 'mennä', 'tulla', 'antaa', 'ottaa', 'ajatella', 'haluta', 'voida', 'täytyä', 'näyttää',
  'puhua', 'kuunnella', 'lukea', 'kirjoittaa', 'syödä', 'juoda', 'nukkua', 'kävellä', 'juosta', 'oppia',
  'ostaa', 'myydä', 'auttaa', 'mies', 'nainen', 'lapsi', 'perhe', 'talo', 'työ', 'päivä',
  'yö', 'aika', 'vuosi', 'viikko', 'kuukausi', 'elämä', 'maa', 'maailma', 'kaupunki', 'paikka',
  'nimi', 'numero', 'kieli', 'historia', 'rakkaus', 'rauha', 'sota', 'ystävä', 'vihollinen', 'ruoka',
  'vesi', 'tuli', 'maa', 'ilma', 'aurinko', 'kuu', 'tähti', 'vuori', 'meri', 'joki',
  'puu', 'kukka', 'punainen', 'valkoinen', 'musta', 'sininen', 'vihreä', 'keltainen', 'yksi', 'kaksi',
  'kolme', 'neljä', 'viisi', 'kuusi', 'seitsemän', 'kahdeksan', 'yhdeksän', 'kymmenen', 'sata', 'tuhat',
  'suuri', 'pieni', 'hyvä', 'huono', 'uusi', 'vanha', 'nopea', 'hidas', 'lämmin', 'kylmä',
  'pitkä', 'lyhyt', 'onnellinen', 'surullinen', 'vahva', 'heikko', 'helppo', 'vaikea', 'kirkas', 'pimeä',
  'tänään', 'eilen', 'huomenna', 'nyt', 'täällä', 'siellä', 'lähellä', 'kaukana', 'ylhäällä', 'alhaalla',
  'edessä', 'takana', 'oikealla', 'vasemmalla', 'myös', 'vain', 'aina', 'joskus', 'ei koskaan', 'paljon',
  'ehkä', 'tietenkin', 'todella', 'siksi', 'miten', 'miksi', 'milloin', 'missä', 'kuka', 'mikä',
  'sydän', 'silmä', 'käsi', 'pää', 'keho', 'terveys', 'sairaus', 'koulu', 'yliopisto', 'kirja',
  'tiede', 'tieto', 'uskonto', 'rukous', 'moskeija', 'kirkko', 'hallitus', 'presidentti', 'laki', 'oikeus',
  'vapaus', 'oikeudenmukaisuus', 'demokratia', 'talous', 'raha', 'markkinat', 'kauppa', 'tie', 'auto', 'lentokone',
  'juna', 'musiikki', 'urheilu', 'taide', 'elokuva', 'teatteri', 'väri', 'muoto', 'koko', 'paino',
  'nopeus', 'energia', 'voima', 'ongelma', 'ratkaisu', 'tulos', 'syy', 'vaikutus', 'ero', 'samankaltaisuus',
];
