export const TOP_200_COMMON_WORDS_GA: readonly string[] = [
  'agus', 'an', 'is', 'i', 'a', 'ar', 'le', 'do', 'ní', 'tá',
  'nach', 'go', 'de', 'sin', 'sé', 'sí', 'siad', 'muid', 'mé', 'tú',
  'sibh', 'ach', 'nó', 'má', 'nuair', 'cad', 'cén', 'cé', 'cáit', 'cén fáth',
  'bheith', 'déanamh', 'rá', 'fhios', 'feiceáil', 'dul', 'teacht', 'tabhairt', 'glacadh', 'smaoineamh',
  'iarraidh', 'ábalta', 'caithfidh', 'breathnú', 'labhairt', 'éisteacht', 'léamh', 'scríobh', 'ithe', 'ól',
  'codladh', 'siúl', 'rith', 'foghlaim', 'ceannach', 'díol', 'cabhair', 'fear', 'bean', 'páiste',
  'teaghlach', 'teach', 'obair', 'lá', 'oíche', 'am', 'bliain', 'seachtain', 'mí', 'saol',
  'tír', 'domhan', 'cathair', 'áit', 'ainm', 'uimhir', 'teanga', 'stair', 'grá', 'síocháin',
  'cogadh', 'cara', 'namhaid', 'bia', 'uisce', 'tine', 'talamh', 'aer', 'grian', 'gealach',
  'réalta', 'sliabh', 'farraige', 'abhainn', 'crann', 'bláth', 'dearg', 'bán', 'dubh', 'gorm',
  'glas', 'buí', 'aon', 'dhá', 'trí', 'ceathair', 'cúig', 'sé', 'seacht', 'ocht',
  'naoi', 'deich', 'céad', 'míle', 'mór', 'beag', 'maith', 'olc', 'nua', 'sean',
  'tapa', 'mall', 'te', 'fuar', 'fada', 'gearr', 'sona', 'brónach', 'láidir', 'lag',
  'éasca', 'deacair', 'geal', 'dorcha', 'inniu', 'inné', 'amárach', 'anois', 'anseo', 'ansiúd',
  'gar', 'i bhfad', 'thuas', 'thíos', 'os comhair', 'taobh thiar', 'ar dheis', 'ar chlé', 'freisin', 'ach amháin',
  'i gcónaí', 'uaireanta', 'riamh', 'go leor', 'b\'fhéidir', 'cinnte', 'go deimhin', 'dá bhrí sin', 'conas', 'cén fáth',
  'cathain', 'cá', 'cé', 'cad', 'croí', 'súil', 'lámh', 'ceann', 'corp', 'sláinte',
  'tinneas', 'scoil', 'ollscoil', 'leabhar', 'eolaíocht', 'eolas', 'reiligiún', 'paidir', 'mosc', 'eaglais',
  'rialtas', 'uachtarán', 'dlí', 'ceart', 'saoirse', 'cóir', 'daonlathas', 'geilleagar', 'airgead', 'margadh',
  'trádáil', 'bóthar', 'carr', 'eitleán', 'traein', 'ceol', 'spórt', 'ealaín', 'scannán', 'amharclann',
];
