export const TOP_200_COMMON_WORDS_MT: readonly string[] = [
  'u', 'il', 'ta\'', 'fil', 'li', 'għal', 'ma', 'minn', 'huwa', 'hija',
  'huma', 'aħna', 'jien', 'int', 'intom', 'iżda', 'jew', 'jekk', 'x\'', 'fejn',
  'meta', 'kif', 'min', 'għaliex', 'dan', 'din', 'dawk', 'dawn', 'ikun', 'kellu',
  'tagħmel', 'jgħid', 'jaf', 'jara', 'jmur', 'jiġi', 'jagħti', 'jieħu', 'jaħseb', 'irid',
  'jista\'', 'għandu', 'jidher', 'jitkellem', 'jisma\'', 'jaqra', 'jikteb', 'jiekol', 'jixrob', 'jorqod',
  'jimxi', 'jiġri', 'jitgħallem', 'jixtri', 'ibiegħ', 'jgħin', 'raġel', 'mara', 'tifel', 'familja',
  'dar', 'xogħol', 'jum', 'lejl', 'ħin', 'sena', 'ġimgħa', 'xahar', 'ħajja', 'pajjiż',
  'dinja', 'belt', 'post', 'isem', 'numru', 'lingwa', 'storja', 'imħabba', 'paċi', 'gwerra',
  'ħabib', 'għadu', 'ikel', 'ilma', 'nar', 'art', 'arja', 'xemx', 'qamar', 'stilla',
  'muntanja', 'baħar', 'xmara', 'siġra', 'fjur', 'aħmar', 'abjad', 'iswed', 'blu', 'aħdar',
  'isfar', 'wieħed', 'tnejn', 'tlieta', 'erbgħa', 'ħamsa', 'sitta', 'sebgħa', 'tmienja', 'disgħa',
  'għaxra', 'mija', 'elf', 'kbir', 'żgħir', 'tajjeb', 'ħażin', 'ġdid', 'qadim', 'mgħaġġel',
  'bil-mod', 'sħun', 'kiesaħ', 'twil', 'qasir', 'ferħan', 'imnikket', 'qawwi', 'dgħajjef', 'faċli',
  'diffiċli', 'ċar', 'mudlam', 'illum', 'il-bieraħ', 'għada', 'issa', 'hawn', 'hemm', 'qrib',
  'bogħod', 'fuq', 'isfel', 'quddiem', 'wara', 'il-lemin', 'ix-xellug', 'ukoll', 'biss', 'dejjem',
  'xi drabi', 'qatt', 'ħafna', 'forsi', 'żgur', 'tassew', 'għalhekk', 'kif', 'għaliex', 'meta',
  'fejn', 'min', 'x\'', 'qalb', 'għajn', 'id', 'ras', 'ġisem', 'saħħa', 'mard',
  'skola', 'università', 'ktieb', 'xjenza', 'għarfien', 'reliġjon', 'talb', 'moskea', 'knisja', 'gvern',
  'president', 'liġi', 'dritt', 'libertà', 'ġustizzja', 'demokrazija', 'ekonomija', 'flus', 'suq', 'kummerċ',
  'triq', 'karozza', 'ajruplan', 'ferrovija', 'mużika', 'sport', 'arti', 'film', 'teatru', 'kulur',
];
