export const TOP_200_COMMON_WORDS_IG: readonly string[] = [
  'na', 'ya', 'ha', 'nke', 'maka', 'ma', 'a', 'ọ', 'n', 'bụ',
  'dị', 'ka', 'si', 'nọ', 'ga', 'nwere', 'ọ bụ', 'ọ dịghị', 'ọ dị', 'ọ ga',
  'm', 'gị', 'ha', 'anyị', 'ụnụ', 'ị', 'ime', 'ikwu', 'ịma', 'ịhụ',
  'ịga', 'ịbịa', 'inye', 'iwe', 'iche', 'achọ', 'ịnwe ike', 'mkpa', 'ị dị ka', 'ikwu okwu',
  'ige ntị', 'ịgụ', 'ide', 'iri', 'ọṅụṅụ', 'ụra', 'ịga ije', 'ịgba ọsọ', 'ịmụta', 'ịzụ ahịa',
  'ire', 'inye aka', 'nwoke', 'nwanyị', 'nwa', 'ezinụlọ', 'ulo', 'ọrụ', 'ụbọchị', 'abalị',
  'oge', 'afọ', 'izu', 'ọnwa', 'ndụ', 'mba', 'ụwa', 'obodo', 'ebe', 'aha',
  'nọmba', 'asụsụ', 'akụkọ ihe mere', 'ịhụnanya', 'udo', 'agha', 'enyi', 'iro', 'nri', 'mmiri',
  'ọkụ', 'ala', 'ikuku', 'anyanwụ', 'ọnwa', 'kpakpando', 'ugwu', 'oké osimiri', 'ọ̀cha', 'osisi',
  'ọcha okwu', 'ọbara ọbara', 'ọcha', 'ojii', 'anụnụ', 'ọcha ọcha', 'ọcha ọcha', 'otu', 'abụọ', 'atọ',
  'anọ', 'ise', 'isii', 'asaa', 'asatọ', 'itoolu', 'iri', 'otu narị', 'otu puku', 'nnọọ',
  'obere', 'mma', 'ọjọọ', 'ọhụrụ', 'ochie', 'ọsọ', 'nwayọọ', 'ọkụ', 'oyi', 'ogologo',
  'mkpumkpu', 'obi ụtọ', 'ụjọ', 'ike', 'adịghị ike', 'dị mfe', 'siri ike', 'ọcha', 'ojii', 'taa',
  'ụnyaahụ', 'echi', 'ugbu a', 'ebe a', 'ebe ahụ', 'nso', 'anya', 'n\'elu', 'n\'ọ̀lụ', 'n\'ụzọ',
  'n\'azụ', 'aka nri', 'aka ekpe', 'kwa', 'naanị', 'mgbe niile', 'mgbe ụfọdụ', 'mgbe ọ bụ otu', 'ọtụtụ', 'ikekwe',
  'n\'ezie', 'ya mere', 'ọ̀ dị ka ọnọdụ', 'n\'ihi ya', 'obi', 'anya', 'aka', 'isi', 'ahụ', 'ahụike',
  'ọrịa', 'ụlọ akwụkwọ', 'mahadum', 'akwụkwọ', 'sayensị', 'ọmụmụ ihe', 'okpukpe', 'ekpere', 'masjid', 'chọọchị',
  'gọọmentin', 'onye isi ala', 'iwu', 'ikike', 'onwe', 'ikpe', 'ọchịchọ onye', 'akụ na ụba', 'ego', 'ahịa',
  'azụmahịa', 'ụzọ', 'ụgbọ ala', 'ụgbọ elu', 'ụgbọ igwe', 'egwu', 'egwuregwu', 'nka', 'ihe nkiri', 'ihe egwuregwu',
];
