export const TOP_200_COMMON_WORDS_IT: readonly string[] = [
  'il', 'di', 'e', 'in', 'un', 'a', 'che', 'è', 'la', 'per',
  'non', 'si', 'una', 'con', 'ma', 'su', 'del', 'al', 'i', 'ho',
  'le', 'lo', 'ha', 'come', 'se', 'tutti', 'lui', 'lei', 'loro', 'noi',
  'io', 'tu', 'voi', 'essere', 'avere', 'fare', 'dire', 'sapere', 'vedere', 'andare',
  'venire', 'dare', 'prendere', 'pensare', 'volere', 'potere', 'dovere', 'sembrare', 'parlare', 'ascoltare',
  'leggere', 'scrivere', 'mangiare', 'bere', 'dormire', 'camminare', 'correre', 'imparare', 'comprare', 'vendere',
  'aiutare', 'uomo', 'donna', 'bambino', 'famiglia', 'casa', 'lavoro', 'giorno', 'notte', 'tempo',
  'anno', 'settimana', 'mese', 'vita', 'paese', 'mondo', 'città', 'posto', 'nome', 'numero',
  'lingua', 'storia', 'amore', 'pace', 'guerra', 'amico', 'nemico', 'cibo', 'acqua', 'fuoco',
  'terra', 'aria', 'sole', 'luna', 'stella', 'montagna', 'mare', 'fiume', 'albero', 'fiore',
  'rosso', 'bianco', 'nero', 'blu', 'verde', 'giallo', 'uno', 'due', 'tre', 'quattro',
  'cinque', 'sei', 'sette', 'otto', 'nove', 'dieci', 'cento', 'mille', 'grande', 'piccolo',
  'buono', 'cattivo', 'nuovo', 'vecchio', 'veloce', 'lento', 'caldo', 'freddo', 'lungo', 'corto',
  'felice', 'triste', 'forte', 'debole', 'facile', 'difficile', 'chiaro', 'scuro', 'oggi', 'ieri',
  'domani', 'ora', 'qui', 'lì', 'vicino', 'lontano', 'sopra', 'sotto', 'davanti', 'dietro',
  'destra', 'sinistra', 'anche', 'solo', 'sempre', 'a volte', 'mai', 'molto', 'forse', 'certo',
  'davvero', 'quindi', 'come', 'perché', 'quando', 'dove', 'chi', 'cosa', 'cuore', 'occhio',
  'mano', 'testa', 'corpo', 'salute', 'malattia', 'scuola', 'università', 'libro', 'scienza', 'conoscenza',
  'religione', 'preghiera', 'moschea', 'chiesa', 'governo', 'presidente', 'legge', 'diritto', 'libertà', 'giustizia',
  'democrazia', 'economia', 'soldi', 'mercato', 'commercio', 'strada', 'macchina', 'aereo', 'treno', 'musica',
];
