export const TOP_200_COMMON_WORDS_SO: readonly string[] = [
  'iyo', 'waa', 'in', 'ee', 'ku', 'ka', 'oo', 'la', 'ah', 'qof',
  'aan', 'u', 'kuma', 'laakiin', 'mise', 'haddii', 'xaggee', 'goorma', 'yaa', 'maxay',
  'isagu', 'iyada', 'iyaga', 'annaga', 'aniga', 'adiga', 'idinka', 'samayn', 'sheegid', 'garanaya',
  'arkayn', 'tegid', 'yimaadid', 'siid', 'qaadid', 'fikirid', 'rabid', 'karaa', 'baahnaan', 'u eegid',
  'hadlidda', 'dhegaysiga', 'akhriska', 'qoridda', 'cunidda', 'cabbidda', 'seexashada', 'socoshada', 'ordidda', 'barasho',
  'iibsashada', 'iibinaynta', 'caawimada', 'nin', 'haweeney', 'cunug', 'qoys', 'guri', 'shaqo', 'maalin',
  'habeenkii', 'wakhti', 'sanadka', 'toddobaadka', 'bilaha', 'nolosha', 'wadan', 'adduunka', 'magaalo', 'goob',
  'magac', 'nambarka', 'luuqadda', 'taariikhda', 'jacaylka', 'nabadda', 'dagaalka', 'saaxiibka', 'cadowga', 'cuntada',
  'biyaha', 'dab', 'dhulka', 'hawo', 'qoraxda', 'dayaxda', 'xiddigta', 'buurta', 'badda', 'webiga',
  'geedka', 'ubaxa', 'cas', 'cad', 'madow', 'buluug', 'cagaaran', 'huruud', 'mid', 'labo',
  'saddex', 'afar', 'shan', 'lix', 'todobo', 'siddeed', 'sagaal', 'toban', 'boqol', 'kun',
  'weyn', 'yar', 'wanaagsan', 'xun', 'cusub', 'gaboobay', 'dhakhso', 'gaabis', 'kulul', 'qabow',
  'dheer', 'gaaban', 'farxadda', 'murugo', 'xoogan', 'daciif', 'fudud', 'adkaa', 'iftiimsan', 'mugdi',
  'maanta', 'shalay', 'berri', 'hadda', 'halkan', 'halkaa', 'dhawaad', 'fog', 'kore', 'hoos',
  'hortii', 'gadaal', 'midig', 'bidix', 'sidoo kale', 'oo keliya', 'had iyo jeer', 'marmarka qaar', 'marna', 'badan',
  'laga yaabaa', 'hubaal', 'runtii', 'sidaas daraadeed', 'sida', 'maxay u', 'goorma', 'xaggee', 'yaa', 'qalbiga',
  'indhaha', 'gacanta', 'madaxa', 'jirka', 'caafimaadka', 'cudurka', 'dugsiga', 'jaamacadda', 'buugga', 'sayniska',
  'aqoonka', 'diinta', 'salaadda', 'masaajidka', 'kaniisadda', 'dowladda', 'madaxweynaha', 'sharciga', 'xuquuqda', 'xorriyadda',
  'caddaaladda', 'dimoqraadiyada', 'dhaqaalaha', 'lacagta', 'suuqa', 'ganacsiga', 'wadada', 'baabuurka', 'diyaaradda', 'tareenka',
  'muusikada', 'ciyaaraha', 'farshaxanka', 'filimka', 'masraxa', 'midabka', 'qaabka', 'baaxadda', 'culayska', 'xawaaraha',
];
