export const TOP_200_COMMON_WORDS_TR: readonly string[] = [
  've', 'bir', 'bu', 'de', 'da', 'için', 'ile', 'o', 'ki', 'var',
  'yok', 'ben', 'sen', 'biz', 'siz', 'onlar', 'ama', 'ya da', 'eğer', 'bu',
  'olmak', 'yapmak', 'söylemek', 'bilmek', 'görmek', 'gitmek', 'gelmek', 'vermek', 'almak', 'düşünmek',
  'istemek', 'olabilmek', 'gerekli', 'görünmek', 'konuşmak', 'dinlemek', 'okumak', 'yazmak', 'yemek', 'içmek',
  'uyumak', 'yürümek', 'koşmak', 'öğrenmek', 'satın almak', 'satmak', 'yardım', 'erkek', 'kadın', 'çocuk',
  'aile', 'ev', 'iş', 'gün', 'gece', 'zaman', 'yıl', 'hafta', 'ay', 'hayat',
  'ülke', 'dünya', 'şehir', 'yer', 'isim', 'sayı', 'dil', 'tarih', 'aşk', 'barış',
  'savaş', 'arkadaş', 'düşman', 'yiyecek', 'su', 'ateş', 'toprak', 'hava', 'güneş', 'ay',
  'yıldız', 'dağ', 'deniz', 'nehir', 'ağaç', 'çiçek', 'kırmızı', 'beyaz', 'siyah', 'mavi',
  'yeşil', 'sarı', 'bir', 'iki', 'üç', 'dört', 'beş', 'altı', 'yedi', 'sekiz',
  'dokuz', 'on', 'yüz', 'bin', 'büyük', 'küçük', 'iyi', 'kötü', 'yeni', 'eski',
  'hızlı', 'yavaş', 'sıcak', 'soğuk', 'uzun', 'kısa', 'mutlu', 'üzgün', 'güçlü', 'zayıf',
  'kolay', 'zor', 'parlak', 'karanlık', 'bugün', 'dün', 'yarın', 'şimdi', 'burada', 'orada',
  'yakın', 'uzak', 'yukarı', 'aşağı', 'önde', 'arkada', 'sağa', 'sola', 'de', 'sadece',
  'her zaman', 'bazen', 'hiçbir zaman', 'çok', 'belki', 'tabii ki', 'gerçekten', 'bu yüzden', 'nasıl', 'neden',
  'ne zaman', 'nerede', 'kim', 'ne', 'kalp', 'göz', 'el', 'kafa', 'vücut', 'sağlık',
  'hastalık', 'okul', 'üniversite', 'kitap', 'bilim', 'bilgi', 'din', 'dua', 'cami', 'kilise',
  'hükümet', 'cumhurbaşkanı', 'kanun', 'hak', 'özgürlük', 'adalet', 'demokrasi', 'ekonomi', 'para', 'pazar',
  'ticaret', 'yol', 'araba', 'uçak', 'tren', 'müzik', 'spor', 'sanat', 'film', 'tiyatro',
  'renk', 'şekil', 'boyut', 'ağırlık', 'hız', 'enerji', 'güç', 'sorun', 'çözüm', 'sonuç',
];
