export const TOP_200_COMMON_WORDS_HA: readonly string[] = [
  'da', 'a', 'na', 'ne', 'ba', 'amma', 'ko', 'sai', 'don', 'wato',
  'shi', 'ita', 'su', 'mu', 'ni', 'kai', 'ku', 'wannan', 'nan', 'can',
  'ce', 'ya', 'ke', 'suna', 'muke', 'kuke', 'suke', 'zai', 'zan', 'za',
  'yi', 'ce', 'sani', 'ga', 'tafi', 'zo', 'bai', 'ɗauka', 'tunani', 'so',
  'iya', 'kamata', 'zama', 'magana', 'ji', 'karanta', 'rubuta', 'ci', 'sha', 'kwana',
  'tafi', 'gudu', 'koyo', 'saya', 'sayar', 'taimaka', 'mutum', 'mace', 'yaro', 'iyali',
  'gida', 'aiki', 'rana', 'dare', 'lokaci', 'shekara', 'mako', 'wata', 'rai', 'ƙasa',
  'duniya', 'birni', 'wuri', 'suna', 'lamba', 'harshe', 'tarihi', 'ƙauna', 'zaman lafiya', 'yaƙi',
  'aboki', 'maƙiyi', 'abinci', 'ruwa', 'wuta', 'ƙasa', 'iska', 'rana', 'wata', 'tauraro',
  'dutse', 'teku', 'kogi', 'itace', 'fure', 'ja', 'fari', 'baki', 'shudi', 'kore',
  'rawaya', 'ɗaya', 'biyu', 'uku', 'huɗu', 'biyar', 'shida', 'bakwai', 'takwas', 'tara',
  'goma', 'ɗari', 'dubu', 'babba', 'ƙarami', 'kyau', 'mugu', 'sabon', 'tsoho', 'sauri',
  'hankali', 'zafi', 'sanyi', 'tsawo', 'gajere', 'farin ciki', 'baƙin ciki', 'ƙarfi', 'rauni', 'sauƙi',
  'wahala', 'haske', 'duhu', 'yau', 'jiya', 'gobe', 'yanzu', 'nan', 'can', 'kusa',
  'nesa', 'sama', 'ƙasa', 'gaba', 'baya', 'dama', 'hagu', 'kuma', 'kawai', 'koyaushe',
  'wani lokaci', 'ba koyaushe', 'da yawa', 'wataƙila', 'tabbas', 'hakika', 'don haka', 'yadda', 'me ya sa', 'yaushe',
  'ina', 'waye', 'zuciya', 'ido', 'hannu', 'kai', 'jiki', 'lafiya', 'cuta', 'makaranta',
  'jami\'a', 'littafi', 'kimiyya', 'ilmi', 'addini', 'sallah', 'masallaci', 'coci', 'gwamnati', 'shugaba',
  'doka', 'haki', 'yanci', 'adalci', 'dimokraɗiyya', 'tattalin arziki', 'kuɗi', 'kasuwa', 'kasuwanci', 'hanya',
  'mota', 'jirgi', 'jirgin ƙasa', 'kiɗa', 'wasanni', 'fasaha', 'fim', 'gidan wasan', 'launi', 'siffa',
];
