export const TOP_200_COMMON_WORDS_PT: readonly string[] = [
  'e', 'o', 'a', 'de', 'que', 'em', 'um', 'é', 'se', 'na',
  'por', 'com', 'não', 'mais', 'mas', 'ao', 'do', 'as', 'dos', 'às',
  'para', 'como', 'tudo', 'este', 'esse', 'ele', 'ela', 'eles', 'nós', 'eu',
  'tu', 'vós', 'ser', 'ter', 'fazer', 'dizer', 'saber', 'ver', 'ir', 'vir',
  'dar', 'tomar', 'pensar', 'querer', 'poder', 'dever', 'parecer', 'falar', 'ouvir', 'ler',
  'escrever', 'comer', 'beber', 'dormir', 'andar', 'correr', 'aprender', 'comprar', 'vender', 'ajudar',
  'homem', 'mulher', 'criança', 'família', 'casa', 'trabalho', 'dia', 'noite', 'tempo', 'ano',
  'semana', 'mês', 'vida', 'país', 'mundo', 'cidade', 'lugar', 'nome', 'número', 'língua',
  'história', 'amor', 'paz', 'guerra', 'amigo', 'inimigo', 'comida', 'água', 'fogo', 'terra',
  'ar', 'sol', 'lua', 'estrela', 'montanha', 'mar', 'rio', 'árvore', 'flor', 'vermelho',
  'branco', 'preto', 'azul', 'verde', 'amarelo', 'um', 'dois', 'três', 'quatro', 'cinco',
  'seis', 'sete', 'oito', 'nove', 'dez', 'cem', 'mil', 'grande', 'pequeno', 'bom',
  'mau', 'novo', 'velho', 'rápido', 'lento', 'quente', 'frio', 'longo', 'curto', 'feliz',
  'triste', 'forte', 'fraco', 'fácil', 'difícil', 'claro', 'escuro', 'hoje', 'ontem', 'amanhã',
  'agora', 'aqui', 'lá', 'perto', 'longe', 'cima', 'baixo', 'frente', 'atrás', 'direita',
  'esquerda', 'também', 'só', 'sempre', 'às vezes', 'nunca', 'muito', 'talvez', 'claro', 'mesmo',
  'então', 'como', 'por que', 'quando', 'onde', 'quem', 'o que', 'coração', 'olho', 'mão',
  'cabeça', 'corpo', 'saúde', 'doença', 'escola', 'universidade', 'livro', 'ciência', 'conhecimento', 'religião',
  'oração', 'mesquita', 'igreja', 'governo', 'presidente', 'lei', 'direito', 'liberdade', 'justiça', 'democracia',
  'economia', 'dinheiro', 'mercado', 'comércio', 'estrada', 'carro', 'avião', 'comboio', 'música', 'desporto',
];
