export const TOP_200_COMMON_WORDS_NO: readonly string[] = [
  'og', 'i', 'det', 'er', 'en', 'til', 'å', 'av', 'som', 'på',
  'de', 'med', 'han', 'hun', 'den', 'vi', 'jeg', 'du', 'ikke', 'men',
  'eller', 'hva', 'der', 'om', 'et', 'var', 'seg', 'sin', 'fra', 'har',
  'kan', 'vil', 'skulle', 'være', 'gjøre', 'si', 'vite', 'se', 'gå', 'komme',
  'gi', 'ta', 'tenke', 'ville', 'la', 'bruke', 'finne', 'starte', 'stoppe', 'mann',
  'kvinne', 'barn', 'familie', 'hus', 'arbeid', 'dag', 'natt', 'tid', 'år', 'uke',
  'måned', 'liv', 'land', 'verden', 'by', 'sted', 'navn', 'nummer', 'språk', 'historie',
  'kjærlighet', 'fred', 'krig', 'venn', 'fiende', 'mat', 'vann', 'ild', 'jord', 'luft',
  'sol', 'måne', 'stjerne', 'fjell', 'hav', 'elv', 'tre', 'blomst', 'rød', 'hvit',
  'svart', 'blå', 'grønn', 'gul', 'en', 'to', 'tre', 'fire', 'fem', 'seks',
  'syv', 'åtte', 'ni', 'ti', 'hundre', 'tusen', 'stor', 'liten', 'god', 'dårlig',
  'ny', 'gammel', 'rask', 'langsom', 'varm', 'kald', 'lang', 'kort', 'glad', 'trist',
  'sterk', 'svak', 'lett', 'tung', 'lys', 'mørk', 'i dag', 'i går', 'i morgen', 'nå',
  'her', 'der', 'nær', 'langt', 'opp', 'ned', 'foran', 'bak', 'høyre', 'venstre',
  'også', 'kun', 'alltid', 'noen ganger', 'aldri', 'mye', 'kanskje', 'selvfølgelig', 'virkelig', 'derfor',
  'hvordan', 'hvorfor', 'når', 'hvor', 'hvem', 'hva', 'hjerte', 'øye', 'hånd', 'hode',
  'kropp', 'helse', 'sykdom', 'skole', 'universitet', 'bok', 'vitenskap', 'kunnskap', 'religion', 'bønn',
  'moske', 'kirke', 'regjering', 'president', 'lov', 'rett', 'frihet', 'rettferdighet', 'demokrati', 'økonomi',
  'penger', 'marked', 'handel', 'vei', 'bil', 'fly', 'tog', 'musikk', 'sport', 'kunst',
  'film', 'teater', 'farge', 'form', 'størrelse', 'vekt', 'hastighet', 'energi', 'kraft', 'problem',
];
