export const TOP_200_COMMON_WORDS_GD: readonly string[] = [
  'agus', 'an', 'is', 'ann', 'a', 'ri', 'le', 'do', 'chan', 'tha',
  'nach', 'gu', 'de', 'sin', 'e', 'i', 'iad', 'sinn', 'mi', 'thu',
  'sibh', 'ach', 'no', 'ma', 'nuair', 'dè', 'dè', 'cò', 'càite', 'carson',
  'bhith', 'dèanamh', 'ràdh', 'fios', 'faicinn', 'dol', 'tighinn', 'toirt', 'gabhail', 'smaoineachadh',
  'iarraidh', 'comasach', 'feumaidh', 'coltach', 'bruidhinn', 'èisteachd', 'leughadh', 'sgrìobhadh', 'ithe', 'òl',
  'cadal', 'coiseachd', 'ruith', 'ionnsachadh', 'ceannach', 'reic', 'cuideachadh', 'fear', 'boireannach', 'pàiste',
  'teaghlach', 'taigh', 'obair', 'là', 'oidhche', 'àm', 'bliadhna', 'seachdain', 'mìos', 'beatha',
  'dùthaich', 'saoghal', 'baile', 'àite', 'ainm', 'àireamh', 'cànan', 'eachdraidh', 'gràdh', 'sìth',
  'cogadh', 'caraid', 'nàmhaid', 'biadh', 'uisge', 'teine', 'talamh', 'àile', 'grian', 'gealach',
  'rionnag', 'beinn', 'muir', 'abhainn', 'craobh', 'flùr', 'dearg', 'geal', 'dubh', 'gorm',
  'uaine', 'buidhe', 'aon', 'dhà', 'trì', 'ceithir', 'còig', 'sia', 'seachd', 'ochd',
  'naoi', 'deich', 'ceud', 'mìle', 'mòr', 'beag', 'math', 'dona', 'ùr', 'sean',
  'luath', 'mall', 'blàth', 'fuar', 'fada', 'goirid', 'toilichte', 'brònach', 'làidir', 'lag',
  'furasta', 'doirbh', 'soilleir', 'dorcha', 'an-diugh', 'an-dè', 'a-màireach', 'a-nis', 'an seo', 'an sin',
  'faisg', 'fada', 'shuas', 'shìos', 'air thoiseach', 'air cùlaibh', 'air an làimh dheis', 'air an làimh chlì', 'cuideachd', 'a-mhàin',
  'an-còmhnaidh', 'uaireannan', 'a-chaoidh', 'mòran', 'dòcha', 'gu dearbh', 'gu fìrinneach', 'mar sin', 'ciamar', 'carson',
  'cuin', 'càite', 'cò', 'dè', 'cridhe', 'sùil', 'làmh', 'ceann', 'corp', 'slàinte',
  'tinneas', 'sgoil', 'oilthigh', 'leabhar', 'saidheans', 'eòlas', 'creideamh', 'ùrnaigh', 'mosg', 'eaglais',
  'riaghaltas', 'ceann-suidhe', 'lagh', 'còir', 'saorsa', 'ceartas', 'deamocrasaidh', 'eaconamaidh', 'airgead', 'margadh',
  'malairt', 'rathad', 'càr', 'plèana', 'trèan', 'ceòl', 'spòrs', 'ealain', 'film', 'taigh-cluich',
];
