export const TOP_200_COMMON_WORDS_IS: readonly string[] = [
  'og', 'í', 'að', 'er', 'sem', 'við', 'með', 'til', 'ekki', 'en',
  'á', 'þetta', 'hann', 'hún', 'þeir', 'við', 'ég', 'þú', 'það', 'af',
  'um', 'eða', 'þegar', 'vera', 'hafa', 'gera', 'segja', 'vita', 'sjá', 'fara',
  'koma', 'gefa', 'taka', 'hugsa', 'vilja', 'geta', 'þurfa', 'líta', 'tala', 'hlusta',
  'lesa', 'skrifa', 'borða', 'drekka', 'sofa', 'ganga', 'hlaupa', 'læra', 'kaupa', 'selja',
  'hjálpa', 'maður', 'kona', 'barn', 'fjölskylda', 'hús', 'vinna', 'dagur', 'nótt', 'tími',
  'ár', 'vika', 'mánuður', 'líf', 'land', 'heimur', 'borg', 'staður', 'nafn', 'tala',
  'tungumál', 'saga', 'ást', 'friður', 'stríð', 'vinur', 'óvinur', 'matur', 'vatn', 'eldur',
  'jörð', 'loft', 'sól', 'tungl', 'stjarna', 'fjall', 'haf', 'á', 'tré', 'blóm',
  'rauður', 'hvítur', 'svartur', 'blár', 'grænn', 'gulur', 'einn', 'tveir', 'þrír', 'fjórir',
  'fimm', 'sex', 'sjö', 'átta', 'níu', 'tíu', 'hundrað', 'þúsund', 'stór', 'lítill',
  'góður', 'slæmur', 'nýr', 'gamall', 'hraður', 'hægur', 'heitur', 'kaldur', 'langur', 'stuttur',
  'glaður', 'sorglegur', 'sterkur', 'veikur', 'auðveldur', 'erfiður', 'bjart', 'dökkt', 'í dag', 'í gær',
  'á morgun', 'núna', 'hér', 'þar', 'nálægt', 'langt', 'upp', 'niður', 'fyrir framan', 'á bak við',
  'til hægri', 'til vinstri', 'einnig', 'aðeins', 'alltaf', 'stundum', 'aldrei', 'mikið', 'kannski', 'auðvitað',
  'virkilega', 'þess vegna', 'hvernig', 'hvers vegna', 'hvenær', 'hvar', 'hverjir', 'hvað', 'hjarta', 'auga',
  'hönd', 'höfuð', 'líkami', 'heilsa', 'veikindi', 'skóli', 'háskóli', 'bók', 'vísindi', 'þekking',
  'trúarbrögð', 'bæn', 'moska', 'kirkja', 'ríkisstjórn', 'forseti', 'lög', 'réttindi', 'frelsi', 'réttlæti',
  'lýðræði', 'efnahagur', 'peningar', 'markaður', 'viðskipti', 'vegur', 'bíll', 'flugvél', 'lest', 'tónlist',
  'íþróttir', 'list', 'kvikmynd', 'leikhús', 'litur', 'form', 'stærð', 'þyngd', 'hraði', 'orka',
];
