export const TOP_200_COMMON_WORDS_SW: readonly string[] = [
  'na', 'ni', 'ya', 'wa', 'kwa', 'katika', 'la', 'za', 'hii', 'hiyo',
  'lakini', 'au', 'kama', 'kwamba', 'yeye', 'wao', 'sisi', 'mimi', 'wewe', 'ninyi',
  'kuwa', 'kufanya', 'kusema', 'kujua', 'kuona', 'kwenda', 'kuja', 'kutoa', 'kuchukua', 'kufikiria',
  'kutaka', 'kuweza', 'lazima', 'kuonekana', 'kuzungumza', 'kusikia', 'kusoma', 'kuandika', 'kula', 'kunywa',
  'kulala', 'kutembea', 'kukimbia', 'kujifunza', 'kununua', 'kuuza', 'kusaidia', 'mtu', 'mwanamke', 'mtoto',
  'familia', 'nyumba', 'kazi', 'siku', 'usiku', 'wakati', 'mwaka', 'wiki', 'mwezi', 'maisha',
  'nchi', 'dunia', 'mji', 'mahali', 'jina', 'nambari', 'lugha', 'historia', 'upendo', 'amani',
  'vita', 'rafiki', 'adui', 'chakula', 'maji', 'moto', 'ardhi', 'hewa', 'jua', 'mwezi',
  'nyota', 'mlima', 'bahari', 'mto', 'mti', 'ua', 'nyekundu', 'nyeupe', 'nyeusi', 'bluu',
  'kijani', 'njano', 'moja', 'mbili', 'tatu', 'nne', 'tano', 'sita', 'saba', 'nane',
  'tisa', 'kumi', 'mia', 'elfu', 'kubwa', 'ndogo', 'nzuri', 'mbaya', 'mpya', 'kongwe',
  'haraka', 'polepole', 'moto', 'baridi', 'ndefu', 'fupi', 'furaha', 'huzuni', 'nguvu', 'dhaifu',
  'rahisi', 'ngumu', 'kung\'aa', 'giza', 'leo', 'jana', 'kesho', 'sasa', 'hapa', 'pale',
  'karibu', 'mbali', 'juu', 'chini', 'mbele', 'nyuma', 'kulia', 'kushoto', 'pia', 'tu',
  'daima', 'wakati mwingine', 'kamwe', 'nyingi', 'labda', 'bila shaka', 'kweli', 'kwa hivyo', 'jinsi', 'kwa nini',
  'lini', 'wapi', 'nani', 'nini', 'moyo', 'jicho', 'mkono', 'kichwa', 'mwili', 'afya',
  'ugonjwa', 'shule', 'chuo kikuu', 'kitabu', 'sayansi', 'ujuzi', 'dini', 'sala', 'msikiti', 'kanisa',
  'serikali', 'rais', 'sheria', 'haki', 'uhuru', 'haki', 'demokrasia', 'uchumi', 'pesa', 'soko',
  'biashara', 'barabara', 'gari', 'ndege', 'treni', 'muziki', 'michezo', 'sanaa', 'filamu', 'ukumbi',
  'rangi', 'umbo', 'ukubwa', 'uzito', 'kasi', 'nishati', 'nguvu', 'tatizo', 'suluhisho', 'matokeo',
];
